### PR TITLE
VIDEOJS: WARN: player.tech().hls is deprecated. Use player.tech().vhs…

### PR DESCRIPTION
**Pull request by DenysNosov**
… instead.

### CODE REVIEW

**Review by esojrafael — APPROVED** [review]
Please pull this changes to the npm version.

**Comment by anschm** [comment]
Please merge this and deploy a new version, thanks

**Comment by LitoMore** [comment]
I think the change should be:

```
const tech = tech(...);
return tech?.hls }} tech?.vhs
```

**Comment by Drabuna** [comment]
Will this be released anytime soon?

**Comment by anschm** [comment]
Could this please mergen? I think this should ne done fast until the API is removed because there are deprecated. After that please provide a new release. The last one is more then 1 year old.

**Pull request closed without merging**
